version: '3.7'

services:
  redis-test:
    container_name: redis-test
    image: 'redis:alpine'
    command:
      - redis-server
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
  postgres-test:
    container_name: postgres-test
    image: postgres:12
    env_file:
      - .test.env
    ports:
      - 5431:5432
    # command: psql -U postgres -c 'set enable_parallel_hash=off;'